### ISSUE TITLE
SyntexError on Android, trying to fix it!

### ISSUE THREAD

**Issue by txs** [rhinos-app/rhinos-app-dev#2]
**What is the current behavior?**
syntexError on android platform
Add a screenshot (if applicable)

**What is the expected behaviour?**

**Steps to reproduce**
trying this solution
http://stackoverflow.com/questions/41058495/syntaxerror-strict-mode-does-not-allow-function-declarations-in-a-lexically-nes/41059867#41059867
1.
2.

**Work around (if any)**

**Environment (include versions)**

OS:
Device:
Browser:
Node version ($ node -v):
NPM version ($ npm -v):

**Other notes**

**Comment by txs** [comment]
the stackoverflow answer works! But it's a module issue. how do we fix it?

**Comment by ngduc** [comment]
@txs That stackoverflow answer works but we don't need it anymore.
I've just upgraded "react-native" to "~0.39.2" which fixed this issue. Do a "$ git pull" and "$ yarn" then try again.

**Comment by txs** [comment]
Cannot fix it with pull, I need to install it again!
I love this package, but hard to install

**Comment by ngduc** [comment]
Of course you'll need to install again after pull :)
This issue is a react-native issue, not caused by this project:
https://github.com/facebook/react-native/issues/11389

**Comment by txs** [comment]
yeah I did the yarn again, but the install was unsuccessful. so I delete the folder and re-clone again

**Comment by txs** [comment]
Thanks for solving my issues
I got it solved!

**Comment by txs** [comment]
I mean I have to delete the folder and re-clone again

Duc Ng <notifications@github.com> 於 2016年12月22日 週四 上午12:47寫道：
